[workspace]
members = [
    "rust-core",
    "rust-orchestration"
]
description = "IDeSyDe Rust suite"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "1.1"

[workspace.package]
version = "0.4.4"
authors = ["Rodolfo Jordao"]
edition = "2021"