name: 'Do a Millw acction'
description: 'Wrapper around common mill usage'
inputs:
  run-dir:
    description: "Where to find millw"
    required: false
    default: "${{ github.workspace }}"
  command:
    description: "the command to issue to mill"
    required: true
runs:
  using: "composite"
  steps:
    - name: Run millw command ${{ inputs.command }}
      if: ${{ runner.os != 'Windows' }}
      run: |
        cd ${{ github.workspace }}
        sh millw tests.test
    - name: Run millw command ${{ inputs.command }}
      if: ${{ runner.os == 'Windows' }}
      run: |
        cd ${{ github.workspace }}
        .\millw.bat tests.test