name: Publish releases for IDeSyDe

on:
  release:
    types: [created]

jobs:
  build-windows-rust:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - name: Build rust
      run: |
        cd ${{ github.workspace }}
        cargo build -r
        cp .\target\release\idesyde-orchestration.exe idesyde.exe
    - name: Cache rust
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}\idesyde.exe
        key: ${{ github.ref }}-${{ runner.os }}-rust-orchestration
  build-linux-rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - name: Build rust
      run: |
        cd ${{ github.workspace }}
        cargo build -r
        cp ./target/release/idesyde-orchestration idesyde
    - name: Cache rust
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/idesyde
        key: ${{ github.ref }}-${{ runner.os }}-rust-orchestration
  build-jars-scala:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Scala 
      uses: olafurpg/setup-scala@v11
      with:
        java-version: "amazon-corretto@1.11.0-11.9.1"
    - name: Build assemblies with sbt
      run: |
        cd ${{ github.workspace }}
        sbt publishModules
    - name: Cache scala
      uses: actions/cache@v2
      with:
        path: |
          ${{ github.workspace }}/imodules/*.jar
          ${{ github.workspace }}/emodules/*.jar
        key: ${{ github.ref }}-scala-modules-jar
  publish-windows-all:
    runs-on: windows-latest
    needs: [build-windows-rust, build-jars-scala]
    steps:
    - uses: actions/checkout@v2
    - id: get_version
      uses: battila7/get-version-action@v2
    - name: Get cached rust
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}\idesyde.exe
        key: ${{ github.ref }}-${{ runner.os }}-rust-orchestration
    - name: Get cached scala
      uses: actions/cache@v2
      with:
        path: |
          ${{ github.workspace }}/imodules/*.jar
          ${{ github.workspace }}/emodules/*.jar
        key: ${{ github.ref }}-scala-modules-jar
    - name: Make zip
      run: |
        cd ${{ github.workspace }}
        Compress-Archive idesyde.exe,emodules,imodules idesyde-windows-amd64.zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}\idesyde-windows-amd64.zip
        asset_name: idesyde-windows-amd64-${{ steps.get_version.outputs.version-without-v }}.zip
        tag: "${{ github.ref }}"
        overwrite: true
        body: "Executable IDeSyDe standalone EXE"
  publish-linux-all:
    runs-on: ubuntu-latest
    needs: [build-windows-rust, build-jars-scala]
    steps:
    - uses: actions/checkout@v2
    - id: get_version
      uses: battila7/get-version-action@v2
    - name: Get cached rust
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/idesyde
        key: ${{ github.ref }}-${{ runner.os }}-rust-orchestration
    - name: Get cached scala
      uses: actions/cache@v2
      with:
        path: |
          ${{ github.workspace }}/imodules/*.jar
          ${{ github.workspace }}/emodules/*.jar
        key: ${{ github.ref }}-scala-modules-jar
    - name: Make zip
      run: |
        cd ${{ github.workspace }}
        Compress-Archive idesyde,emodules,imodules idesyde-linux-amd64.zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}\idesyde-linux-amd64.zip
        asset_name: idesyde-linux-amd64-${{ steps.get_version.outputs.version-without-v }}.zip
        tag: "${{ github.ref }}"
        overwrite: true
        body: "Executable IDeSyDe standalone EXE"
  # publish-linux-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - id: get_version
  #     uses: battila7/get-version-action@v2
  #   - name: Set up JDK 
  #     uses: olafurpg/setup-scala@v11
  #     with:
  #       java-version: "amazon-corretto@1.11.0-11.9.1"
  #   - name: Build assembly with sbt
  #     run: |
  #       cd ${{ github.workspace }}
  #       sbt "Universal / packageBin"
  #   - name: Upload binaries to release
  #     uses: svenstaro/upload-release-action@v2
  #     with:
  #       repo_token: ${{ secrets.GITHUB_TOKEN }}
  #       file: ${{ github.workspace }}/scala-cli/target/universal/cli-${{ steps.get_version.outputs.version-without-v }}.zip
  #       asset_name: idesyde-${{ steps.get_version.outputs.version-without-v }}-linux.zip
  #       tag: "${{ github.ref }}"
  #       overwrite: true
  #       body: "Executable IDeSyDe standalone linux ZIP"
