# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test PyOxidizer for IDeSyDe

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test-linux:
    env:
      PYTHON_VERSION: 3.9
      POETRY_VERSION: 1.1.5
      RUST_VERSION: 1.49.0
      PYOXIDIZER_VERSION: 0.11.0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Set up pip properly (Linux)
      run: |
        python -m pip install --upgrade pip
        pip install subprocess32
    - uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: ${{ env.POETRY_VERSION }}
    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1.0.4
      with:
        rust-version: ${{ env.RUST_VERSION }}
    - name: Install PyOxidizer
      run: cargo install --version ${{ env.PYOXIDIZER_VERSION }} pyoxidizer
    - name: Regen Setup.py from poetry file
      run: |
        cd $GITHUB_WORKSPACE
        poetry update
        poetry export -o requirements.txt
    - name: Run PyOxidizer
      run: |
        cd $GITHUB_WORKSPACE
        pyoxidizer build
  test-windows:
    env:
      PYTHON_VERSION: 3.9
      POETRY_VERSION: 1.1.5
      RUST_VERSION: 1.49.0
      PYOXIDIZER_VERSION: 0.11.0
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Set up pip properly
      run: python -m pip install --upgrade pip
    - uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: ${{ env.POETRY_VERSION }}
    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1.0.4
      with:
        rust-version: ${{ env.RUST_VERSION }}
    - name: Install PyOxidizer
      run: cargo install --version ${{ env.PYOXIDIZER_VERSION }} pyoxidizer
    - name: Regen Setup.py from poetry file
      run: |
        cd $GITHUB_WORKSPACE
        poetry update
        poetry export -o requirements.txt
    - name: Run PyOxidizer
      run: |
        cd $GITHUB_WORKSPACE
        pyoxidizer build
  test-apple:
    env:
      PYTHON_VERSION: 3.9
      POETRY_VERSION: 1.1.5
      RUST_VERSION: 1.49.0
      PYOXIDIZER_VERSION: 0.11.0
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Set up pip properly
      run: python -m pip install --upgrade pip
    - uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: ${{ env.POETRY_VERSION }}
    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1.0.4
      with:
        rust-version: ${{ env.RUST_VERSION }}
    - name: Install PyOxidizer
      run: cargo install --version ${{ env.PYOXIDIZER_VERSION }} pyoxidizer
    - name: Regen Setup.py from poetry file
      run: |
        cd $GITHUB_WORKSPACE
        poetry update
        poetry export -o requirements.txt
    - name: Run PyOxidizer
      run: |
        cd $GITHUB_WORKSPACE
        pyoxidizer build
