---
name: "Testing known case studies"

on:
  push:
    branches:
      - "master"
      - "develop"

jobs:
  test-java-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: ["openjdk@1.11.0", "openjdk@1.15.0", "openjdk@1.17.0", "graalvm@"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: olafurpg/setup-scala@v11
      with:
        java-version: ${{ matrix.java }}
        # server-id: io.github.forsyde # Value of the distributionManagement/repository/id field of the pom.xml
        # settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Tests with sbt (All)
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        cd ${{ github.workspace }}
        millw tests.test
    - name: Tests with sbt (All)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        cd ${{ github.workspace }}
        millw.bat tests.test