---
name: "Building executables"

on:
  push:
    branches:
      - "master"
      - "develop"

jobs:
  publish-linux-pyz:
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
        poetry: [1.1.5]
        rust: [1.49.0]
        pyoxidizer: [0.11.0]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Set up pip properly
      run: python -m pip install --upgrade pip
    - uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: ${{ matrix.poetry }}
    - name: Make shiv from poetry file
      run: |
        cd ${{ github.workspace }}
        poetry update
        poetry install
        mkdir -p dist
        poetry run shiv --site-packages=$(find $(poetry env info -p) -name "site-packages") --upgrade -o dist/idesyde.pyz -c idesyde idesyde
  publish-linux-bin:
    env:
      PYTHON_VERSION: 3.8
      POETRY_VERSION: 1.1.5
      RUST_VERSION: 1.49.0
      PYOXIDIZER_VERSION: 0.11.0
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Set up pip properly
      run: python -m pip install --upgrade pip
    - uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: ${{ env.POETRY_VERSION }}
    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1.0.4
      with:
        rust-version: ${{ env.RUST_VERSION }}
    - name: Install PyOxidizer
      run: cargo install --version ${{ env.PYOXIDIZER_VERSION }} pyoxidizer
    - name: Run PyOxidizer
      run: |
        cd ${{ github.workspace }}
        pyoxidizer build --release
  publish-windows-pyz:
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
        poetry: [1.1.5]
        rust: [1.49.0]
        pyoxidizer: [0.11.0]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Set up pip properly
      run: python -m pip install --upgrade pip
    - uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: ${{ matrix.poetry }}
    - name: Make shiv from poetry file
      run: |
        cd ${{ github.workspace }}
        poetry update
        poetry install
        mkdir -p dist
        poetry run shiv -o dist\idesyde.pyz -c idesyde idesyde
  publish-windows-bin:
    env:
      PYTHON_VERSION: 3.9
      POETRY_VERSION: 1.1.5
      RUST_VERSION: 1.49.0
      PYOXIDIZER_VERSION: 0.11.0
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Set up pip properly
      run: python -m pip install --upgrade pip
    - uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: ${{ env.POETRY_VERSION }}
    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1.0.4
      with:
        rust-version: ${{ env.RUST_VERSION }}
    - name: Install PyOxidizer
      run: cargo install --version ${{ env.PYOXIDIZER_VERSION }} pyoxidizer
    - name: Run PyOxidizer
      run: |
        cd ${{ github.workspace }}
        pyoxidizer build --release
  publish-apple-pyz:
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
        poetry: [1.1.5]
        rust: [1.49.0]
        pyoxidizer: [0.11.0]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Set up pip properly
      run: python -m pip install --upgrade pip
    - uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: ${{ matrix.poetry }}
    - name: Regen Setup.py from poetry file
      run: |
        cd ${{ github.workspace }}
        poetry update
        poetry install
        mkdir -p dist
        poetry run shiv --site-packages=$(find $(poetry env info -p) -name "site-packages") --upgrade -o dist/idesyde.pyz -c idesyde idesyde
  publish-apple-bin:
    env:
      PYTHON_VERSION: 3.9
      POETRY_VERSION: 1.1.5
      RUST_VERSION: 1.49.0
      PYOXIDIZER_VERSION: 0.11.0
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Set up pip properly
      run: python -m pip install --upgrade pip
    - uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: ${{ env.POETRY_VERSION }}
    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1.0.4
      with:
        rust-version: ${{ env.RUST_VERSION }}
    - name: Install PyOxidizer
      run: cargo install --version ${{ env.PYOXIDIZER_VERSION }} pyoxidizer
    - name: Regen Setup.py from poetry file
      run: |
        cd ${{ github.workspace }}
        poetry update
        poetry export -o requirements.txt
    - name: Run PyOxidizer
      run: |
        cd ${{ github.workspace }}
        pyoxidizer build --release
